### ISSUE TITLE
cuda out of memory rtx4070 with 6 images

### ISSUE THREAD

**Issue by Pepslee** [facebookresearch/vggt#39]
I use 6 images and dtype = torch.float16 and get 
`CUDA out of memory. Tried to allocate 20.00 MiB. GPU`

``` python

import torch
from vggt.models.vggt import VGGT
from vggt.utils.load_fn import load_and_preprocess_images

device = "cuda" if torch.cuda.is_available() else "cpu"
# bfloat16 is supported on Ampere GPUs (Compute Capability 8.0+)
dtype = torch.float16

# Initialize the model and load the pretrained weights.
# This will automatically download the model weights the first time it's run, which may take a while.
model = VGGT.from_pretrained("facebook/VGGT-1B").to(device)

# Load and preprocess example images (replace with your own image paths)
image_names = ["img1.jpg", "img2.jpg", "img3.jpg", "img4.jpg", "img5.jpg", "img6.jpg" ]

images = load_and_preprocess_images(image_names).to(device)

with torch.no_grad():
    with torch.cuda.amp.autocast(dtype=dtype):
        # Predict attributes including cameras, depth maps, and point maps.
        predictions = model(images)


```
Runtime and GPU Memory table says that with 8GB I should be able to run 20-30 images.
Maybe I understand something wrong or doing something wrong?

**Comment by jytime** [comment]
Hi @Pepslee ,

Could you check how much GPU memory is consumed after loading the model weights (before inference starts)?

If it uses significant GPU memory, you might consider converting the model weights to half-precision (torch.float16) by doing:
```
model = model.to(dtype)
```
, which should help avoid some problems. 

For more details, can you check the points in https://github.com/facebookresearch/vggt/issues/11?

**Comment by Pepslee** [comment]
@jytime 
```model = VGGT.from_pretrained("facebook/VGGT-1B").to(device)```
uses 4976MiB /   8188MiB
If I convert fomel to float16
```model = VGGT.from_pretrained("facebook/VGGT-1B").to(torch.float16).to(device)```
I get error:
```shell
vggt/.venv/bin/python /home/serg/PycharmProjects/vggt/main.py 
Traceback (most recent call last):
  File "/home/serg/PycharmProjects/vggt/main.py", line 23, in <module>
    predictions = model(images)
                  ^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/vggt/models/vggt.py", line 69, in forward
    pose_enc_list = self.camera_head(aggregated_tokens_list)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/vggt/heads/camera_head.py", line 100, in forward
    pose_tokens = self.token_norm(pose_tokens)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/modules/normalization.py", line 201, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "/home/serg/PycharmProjects/vggt/.venv/lib/python3.12/site-packages/torch/nn/functional.py", line 2573, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: expected scalar type Float but found Half
```

**Comment by jytime** [comment]
The problem of `RuntimeError: expected scalar type Float but found Half` can be solved by removing this decorator:

https://github.com/facebookresearch/vggt/blob/ae1b9c87507ea53c111c0bc79c20fb601d6ac283/vggt/models/vggt.py#L67

**Comment by Pepslee** [comment]
@jytime  Thank you, it works after I changed
    dpt_head  -> _apply_pos_embed   
from ` return x + pos_embed` to ` return x + pos_embed.to(x.dtype)`
For some reason it converts the data type to float32 if I don`t convert it manualy
